
spring:
  application:
    mode: dev
    version: v0

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      readinessstate:
        enabled: true