apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app # User 서비스 라벨
    spec:
      containers:
        - name: user-app
          image: jcho5078/user-app:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PRODUCT_HOST
              value: product-app-service