apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app # Product 서비스 라벨
    spec:
      containers:
        - name: product-app
          image: jcho5078/product-app:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"