
spring:
  application:
    mode: ${APP_MODE}
    version: ${APP_VERSION}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      readinessstate:
        enabled: true

env:
  app-mod: ${APP_MODE}
  app-version: ${APP_VERSION}