apiVersion: v1
kind: Service
metadata:
  name: product-app-service
spec:
  selector:
    app: product-app # Product Deployment의 라벨을 선택
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP