# 기존 ingress 삭제 후, helm upgrade --install user-app-prod ./user-app -f ./user-app/values-prod.yaml
replicaCount: 3

#image:
#  tag: prod-latest
#  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

config:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql:////prod-db:3306/userdb"
  SPRING_DATASOURCE_USERNAME: "admin"

secrets:
  SPRING_DATASOURCE_PASSWORD: "supersecret"