# user-app/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# [1] Kustomize가 처리할 리소스 목록 (Generator가 관리하지 않는 파일만 포함)
# user-deployment.yaml, user-service.yaml, user-ingress.yaml 등만 포함합니다.
resources:
  - user-deployment.yaml
# - base/user-service.yaml  # 필요하다면 추가

# [2] ConfigMap Generator (일반 설정)
# base/app-config.yaml 내용을 읽어 해시를 포함한 ConfigMap을 생성합니다.
# ConfigMap 내용이 변경되면, Deployment가 자동으로 롤아웃됩니다.
configMapGenerator:
  - name: app-config
    envs:
      - .config.env

# [3] Secret Generator (DB 인증 정보)
# base/spring-db-secret.yaml 내용을 읽어 해시를 포함한 Secret을 생성합니다.
# Secret 내용이 변경되면, Deployment가 자동으로 롤아웃됩니다.
secretGenerator:
  - name: spring-db-secret
    envs:
      - .db-secret.env