apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app # User 서비스 라벨
    spec:
      containers:
        - name: user-app
          image: jcho5078/user-app:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            # 1. ConfigMap 참조 (일반 설정)
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: app-config # Kustomize가 자동으로 app-config-<hash>로 변경
                  key: APP_MODE
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_VERSION
            # 2. Secret 참조 (DB 인증 정보)
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: spring-db-secret # Kustomize가 자동으로 spring-db-secret-<hash>로 변경
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: spring-db-secret # Kustomize가 자동으로 spring-db-secret-<hash>로 변경
                  key: DB_PASS
            # 3. 다른 Service 호스트 (내부 통신 설정)
            - name: PRODUCT_HOST
              value: product-app-service